### ISSUE TITLE
Formula using Flow Template Type - Getting Error Node Flow Template is invalid

### ISSUE THREAD

**Issue by rsrinivasanhome** [simonec73/threatsmanager#30] opened 2022-02-03 07:37 UTC
**Describe the bug**
I have migrated my template from MTMT.  Some of the rule(s) involved flow templates.  I found those formulas are not working.
I am not sure if this is a bug but when I open the formula in the formula editor this is what I see

![image](https://user-images.githubusercontent.com/31912418/152302614-7a1537c2-bf8c-4b56-b29c-5f0883c95f4f.png)

Short Title of threat - "An adversary may spoof an Azure administrator and gain access to Azure subscription portal"

Is there any workaround ?
[AzureTemplate_simulatedSample.tb7.txt](https://github.com/simonec73/threatsmanager/files/7992757/AzureTemplate_simulatedSample.tb7.txt)

**Comment by simonec73** [comment] 2022-02-03 17:06
Confirmed. That's a bug. I have no workaround for now.

**Comment by rsrinivasanhome** [comment] 2022-03-01 09:47
Do we have any idea when the fix will be available ?

**Comment by simonec73** [comment] 2022-03-11 15:59
Hi, it's in my backlog. No I do not have any planned time because it is going to be fixed with the next major release.

**Closed by simonec73** 2022-03-11 15:59 UTC

**Comment by rsrinivasanhome** [comment] 2022-07-05 05:52
@simonec73   when is the next major release planned ?

**Comment by simonec73** [comment] 2022-07-06 11:22
No date has been planned yet.
